# -*- coding: utf-8 -*-
################################################################################
## Form generated from reading UI file 'help_windowiduSZA.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractScrollArea, QApplication, QLabel, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QVBoxLayout,
    QWidget)

class Ui_HelpWindow(object):
    def setupHelpUi(self, HelpWindow):
        if not HelpWindow.objectName():
            HelpWindow.setObjectName(u"HelpWindow")
        self.centralwidget = QWidget(HelpWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFocusPolicy(Qt.WheelFocus)
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, -1885, 1700, 3034))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy1)
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.label = QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(u"label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)
        self.label.setMaximumSize(QSize(16777215, 16777215))
        self.label.setFocusPolicy(Qt.WheelFocus)
        self.label.setLayoutDirection(Qt.LeftToRight)
        self.label.setTextFormat(Qt.AutoText)
        self.label.setScaledContents(True)
        self.label.setWordWrap(True)
        self.label.setMargin(0)
        self.label.setIndent(0)

        self.verticalLayout_2.addWidget(self.label)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.verticalLayout.addWidget(self.scrollArea)

        self.return_button_help = QPushButton(self.centralwidget)
        self.return_button_help.setObjectName(u"return_button_help")
        sizePolicy3 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Minimum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.return_button_help.sizePolicy().hasHeightForWidth())
        self.return_button_help.setSizePolicy(sizePolicy3)
        self.return_button_help.setMaximumSize(QSize(16777215, 60))
        self.return_button_help.setStyleSheet(u"QPushButton {\n"
                                              "  align-items: left;\n"
                                              "  background-color: #c2fab1;\n"
                                              "  border: 2px solid #111;\n"
                                              "  border-radius: 8px;\n"
                                              "  box-sizing: border-box;\n"
                                              "  color: #111;\n"
                                              "  cursor: pointer;\n"
                                              "  display: flex;\n"
                                              "  font-family: Inter,sans-serif;\n"
                                              "  font-size: 16px;\n"
                                              # "  height: 100px;\n"
                                              # "  line-height: 300px;\n"
                                              # "  max-width: 300%;\n"
                                              "  padding: 0 25px;\n"
                                              "  position: relative;\n"
                                              "  text-align: center;\n"
                                              "  text-decoration: none;\n"
                                              "  user-select: none;\n"
                                              "  -webkit-user-select: none;\n"
                                              "  touch-action: manipulation;\n"
                                              "}")

        self.verticalLayout.addWidget(self.return_button_help)

        HelpWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(HelpWindow)

        QMetaObject.connectSlotsByName(HelpWindow)
        # setupUi

    def retranslateUi(self, HelpWindow):
        HelpWindow.setWindowTitle(QCoreApplication.translate("HelpWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("HelpWindow",
                                                      u"<html><head/><body><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:16pt; font-weight:700;\">Educational &amp; Research Game for Studying Emergent Intelligence</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:16pt; font-weight:700;\">&quot;Ants VS Spiders&quot;</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:16pt; font-weight:700;\">Find out, when Collective Intelligence wins!</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">1. Objective</span></p><p align=\"justify\">The objective of Educational Game is to provide users with opportunity for experimentally study the theory of Emergent Intelligence (EI) \u2013 new area of Collective Intelligence of open self-organized systems, based on non-equilibrium thermodynamics. </p><p align=\"justify\">The game is based on ontologies and multi-agent technology and makes possi"
                                                      "ble to implement and compare the results of individual and collective coordinated decision-making both in terms of the movement and delivery of relatively large heavy food by ants to the anthill, exceeding their individual capabilities, and collective confrontation for protection from spiders with more powerful capabilities \u2013 to demonstrate that Collective Intelligence wins. </p><p align=\"justify\">The game is intended for software engineers, researchers, PhD, students and schoolchildren, who study collective AI programming. </p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">2. Application</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The developed system can be used both in computer science classes in high school and in first years of university, for example, in the courses of \u201cArtificial Intelligence\u201d, \u201cSoftware Engineering\u201d, etc.</span></p><p align=\"justify\"><sp"
                                                      "an style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">At the moment system can be applied on stage 1 and stage 2 is under development.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The developed system is designed as open system and can be provided to partners and end-users as a digital platform with open source code for joint developments.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">3. The world of Ants and Spiders</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The world of software agents was created to model the simplest digital ecosystem with colonies of ants and spiders, which show the competition and cooperation as in any natural ecosystem.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">How the world of ants and spiders works:</span></p><p align=\"j"
                                                      "ustify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 The anthill gives birth to ants based on the food supply (apples) available in them.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Ants are born and go out in search of food.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Ants spend their energy moving and when they don\u2019t find food, they die.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 If an ant finds food, it looks at its size (weight).</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Large food can only be carried by a few ants.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Food gives vitality to the ant, but its main goal is to deliver maximum food to th"
                                                      "e anthill.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 To move large amounts of food, the ant assembles a team.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 When choosing which team to be on, the ant focuses on the maximum result for its anthill.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Similarly, spiders are constantly being born, looking for ants for their food.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Not finding ants, some of the spiders die.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 Ants can also form teams to protect themselves from spiders.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 The ant joins the team t"
                                                      "o protect against the spider where the maximum result is planned, i.e. What is most valued is defeating the biggest (terrible) spider.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 If an ant leaves a team to join another, he coordinates his decision with the previous team so that it can find a replacement for him.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 If the number of spiders decreases, the ant colony increases (and vice versa).</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2022 And all these processes are continuously repeated until one of the colonies wins.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The main objective of the system is to show that collective consensus decision-making by agents significantly outperforms their individual decision-making. </spa"
                                                      "n></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The system's capabilities show that collective interaction allows you to achieve higher results and win the game even where the physical attributes of entities are significantly weaker than the enemy.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The proposed collection tasks for experiments show that the more collective decisions are made by ants, the longer their colonies live and prosper and, conversely, the more they act separately, individually (one at a time), the sooner they die.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">4. Functionality of main menu </span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">The main menu is presented on the top line of the screen and is always available for use; pressing any key or clicking the "
                                                      "mouse stops the simulation:</span></p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Settings </span>\u2013 setting parameters for simulation </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-style:italic;\">Spiders Settings</span></p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Radius - </span>allows the user to change the vision radius of the spiders (min: 0, max: 1000) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Speed - </span>allows the user to change the speed of the spiders (min: 0, max: 50) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Return </span>\u2013 exit submenu with no changes </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font"
                                                      "-weight:700;\">Apply</span> \u2013 apply changes </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-style:italic;\">Ants Settings</span></p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Radius- </span>allows the user to change the vision radius of the ants (min: 0, max: 1000) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Speed - </span>allows the user to change the speed of the ants (min: 0, max: 50) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Return</span> \u2013 exit submenu with no changes </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Apply</span> \u2013 apply changes </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-"
                                                      "style:italic;\">System Settings</span></p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Time gap between apple spawns \u2013 </span>allows the user to change the frequency of adding apples (min: 10, max: 1000) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Gap between spider spawn -</span> allows the user to change the frequency of adding spiders (min: 10, max: 1000) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Start number of ants -</span> allows the user to change start number of ants (min: 0, max: 100) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Start number of spiders -</span> allows the user to change start number of spiders (min: 0, max: 100) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" fon"
                                                      "t-weight:700;\">Start number of apples -</span> allows the user to change start number of apples (min: 0, max: 100) </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Return </span>\u2013 exit submenu with no changes </p><p align=\"justify\"><span style=\" font-family:'Wingdings';\">\u00a7</span><span style=\" font-weight:700;\">Apply </span>\u2013 apply changes </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-style:italic;\">Back</span>- exit submenu </p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Start/ Continue </span>\u2013 starts and continue the simulation process for a generated scene based on game settings. Display actual game process </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Back \u2013 return to menu </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Re"
                                                      "start \u2013 restart simulation </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Collective intelligence: on/off \u2013 on or off collective intelligence </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Pause \u2013 set game on pause or resume it </p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Decision making log</span> \u2013 log of MAS decisions </p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Results </span>\u2013 display of modeling results and graphs of changes in the main parameters of the states of the game world </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Graph of accumulated energy of ants </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Graph of accumulated energy of spiders </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Graph of ene"
                                                      "rgy of anthill </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span>Graph of the number of system messages per time tick </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-style:italic;\">Back</span> - exit submenu </p><p align=\"justify\"><span style=\" font-family:'Courier New';\">o</span><span style=\" font-weight:700; font-style:italic;\">Download Graphs </span>\u2013 download results as .xlsx file </p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Help</span> \u2013 explains and shows all the features of the game </p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-weight:700;\">Exit </span>\u2013 exit system </p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">5. Collection of tasks for Stage 1</span></p><p align=\"justify\"><span style=\" font-family:'Symb"
                                                      "ol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Explores predefined downloadable examples of scenes of the digital world of spiders and ants to build important dependencies:</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">How does the speed of ants and spiders affect the results of the system;</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">How does the vision radius of ants and spiders affect the results of the system;</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">How does the energy consumption of an ant and a spider affect the results of the system;</span></p><p align=\"justify\"><spa"
                                                      "n style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Complicate the process of making collective decisions of ants to evaluate their impact on the results of the system:</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Ants act purely individually, without any collective interaction;</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Ants gather in teams to bring large amounts of food together;</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Ants form a team to fight spiders;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</sp"
                                                      "an><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Create conditions under which ants win;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Create conditions under which spiders win;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Create conditions where a balance is established between ants and spiders;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Create conditions where the number of ants and spiders oscillates rhythmically;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Show and explain other inter"
                                                      "esting phenomena you discovered.</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">6. Prospects</span></p><p align=\"justify\">The system is under development now but is intended for step-by-step way application at the following levels: </p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">Stage 1</span><span style=\" font-family:'Courier New'; font-weight:700;\"> \u2013 </span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">obtaining a first understanding of multi-agent systems and studying the processes of self-organization in complex systems such as natural ecosystems, in which processes of competition and cooperation of participants are observed;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman',"
                                                      "'serif'; font-size:12pt; font-weight:700;\">Stage 2 </span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2013 obtaining a first understanding of ontologies that help build formalized knowledge models of domain areas and use the ontologies for setting up and developing multi-agent systems;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">Stage 3</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">\u2013 studying the basics of multi-agent programming and expanding the world of the proposed system through the introduction of new proprietary software agents of the participants and protocols for their interaction;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol';\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">Stage 4</span><span style=\" font-family:'Times New Roman',"
                                                      "'serif'; font-size:12pt;\">\u2013 study and development of models and methods for collective decision-making of agents to achieve a state of \u201ccompetitive equilibrium\u201d (consensus).</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt; font-weight:700;\">7. Technical requirements</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Below is a list of recommended application server hardware and software requirements:</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">RAM: 8 GB or more;</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Python 3 with installed libraries:</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span"
                                                      " style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Pygame</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Thespian</span></p><p align=\"justify\"><span style=\" font-family:'Courier New'; font-size:12pt;\">o</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Matplotlib</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">processor: 4 x 2.4 GHz and higher;</span></p><p align=\"justify\"><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">Below is a list of recommended application client hardware and software requirements:</span></p><p align=\"justify\"><span style=\" font-family:'Symbol'; font-size:12pt;\">\u00b7</span><span style=\" font-family:'Times New Roman','serif'; font-size:12pt;\">RAM: 4 GB or more;</spa"
                                                      "n></p><p align=\"justify\"><br/></p></body></html>", None))
        self.return_button_help.setText(QCoreApplication.translate("HelpWindow", u"Return", None))
    # retranslateUi

