locale: "ru"

system:
  generation: True
  apple_spawn_time: 100
  spider_spawn_time: 120
  ant_spawn_time: 60
  ant_num: 70
  spider_num: 10
  apple_num: 5
  max_ants_num: 150
  max_spiders_num: 15
  max_apples_num: 20

ant:
  speed: 4.25
  radius: 70

spider:
  speed: 4.5
  radius: 70
