locale: "ru"

system:
  generation: False
  apple_spawn_time: 100
  spider_spawn_time: 120
  ant_spawn_time: 60
  ant_num: 50
  spider_num: 3
  apple_num: 5
  max_ants_num: 150
  max_spiders_num: 15
  max_apples_num: 20

ant:
  speed: 2.25
  radius: 70

spider:
  speed: 2.5
  radius: 70
